/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpdatePasswordRouteImport } from './routes/update-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedNewsRouteImport } from './routes/_authenticated/news'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated/_student'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedStudentStationaryRouteImport } from './routes/_authenticated/_student/stationary'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated/_student/profile'
import { Route as AuthenticatedStudentPortableRouteImport } from './routes/_authenticated/_student/portable'
import { Route as AuthenticatedStudentBookingRouteImport } from './routes/_authenticated/_student/booking'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin/index'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin/users'
import { Route as AuthenticatedAdminAdminStatisticsRouteImport } from './routes/_authenticated/_admin/admin/statistics'
import { Route as AuthenticatedAdminAdminScheduleRouteImport } from './routes/_authenticated/_admin/admin/schedule'
import { Route as AuthenticatedAdminAdminRequestsRouteImport } from './routes/_authenticated/_admin/admin/requests'
import { Route as AuthenticatedAdminAdminProjectsRouteImport } from './routes/_authenticated/_admin/admin/projects'
import { Route as AuthenticatedAdminAdminNewsRouteImport } from './routes/_authenticated/_admin/admin/news'
import { Route as AuthenticatedAdminAdminEquipmentRouteImport } from './routes/_authenticated/_admin/admin/equipment'
import { Route as AuthenticatedAdminAdminBookingsRouteImport } from './routes/_authenticated/_admin/admin/bookings'

const UpdatePasswordRoute = UpdatePasswordRouteImport.update({
  id: '/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNewsRoute = AuthenticatedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentStationaryRoute =
  AuthenticatedStudentStationaryRouteImport.update({
    id: '/stationary',
    path: '/stationary',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentPortableRoute =
  AuthenticatedStudentPortableRouteImport.update({
    id: '/portable',
    path: '/portable',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentBookingRoute =
  AuthenticatedStudentBookingRouteImport.update({
    id: '/booking',
    path: '/booking',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminStatisticsRoute =
  AuthenticatedAdminAdminStatisticsRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminScheduleRoute =
  AuthenticatedAdminAdminScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminRequestsRoute =
  AuthenticatedAdminAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminProjectsRoute =
  AuthenticatedAdminAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminNewsRoute =
  AuthenticatedAdminAdminNewsRouteImport.update({
    id: '/news',
    path: '/news',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminEquipmentRoute =
  AuthenticatedAdminAdminEquipmentRouteImport.update({
    id: '/equipment',
    path: '/equipment',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminBookingsRoute =
  AuthenticatedAdminAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/news': typeof AuthenticatedNewsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/booking': typeof AuthenticatedStudentBookingRoute
  '/portable': typeof AuthenticatedStudentPortableRoute
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/stationary': typeof AuthenticatedStudentStationaryRoute
  '/admin/bookings': typeof AuthenticatedAdminAdminBookingsRoute
  '/admin/equipment': typeof AuthenticatedAdminAdminEquipmentRoute
  '/admin/news': typeof AuthenticatedAdminAdminNewsRoute
  '/admin/projects': typeof AuthenticatedAdminAdminProjectsRoute
  '/admin/requests': typeof AuthenticatedAdminAdminRequestsRoute
  '/admin/schedule': typeof AuthenticatedAdminAdminScheduleRoute
  '/admin/statistics': typeof AuthenticatedAdminAdminStatisticsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/news': typeof AuthenticatedNewsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/booking': typeof AuthenticatedStudentBookingRoute
  '/portable': typeof AuthenticatedStudentPortableRoute
  '/profile': typeof AuthenticatedStudentProfileRoute
  '/stationary': typeof AuthenticatedStudentStationaryRoute
  '/admin/bookings': typeof AuthenticatedAdminAdminBookingsRoute
  '/admin/equipment': typeof AuthenticatedAdminAdminEquipmentRoute
  '/admin/news': typeof AuthenticatedAdminAdminNewsRoute
  '/admin/projects': typeof AuthenticatedAdminAdminProjectsRoute
  '/admin/requests': typeof AuthenticatedAdminAdminRequestsRoute
  '/admin/schedule': typeof AuthenticatedAdminAdminScheduleRoute
  '/admin/statistics': typeof AuthenticatedAdminAdminStatisticsRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/update-password': typeof UpdatePasswordRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/news': typeof AuthenticatedNewsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_public/': typeof PublicIndexRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/_authenticated/_student/booking': typeof AuthenticatedStudentBookingRoute
  '/_authenticated/_student/portable': typeof AuthenticatedStudentPortableRoute
  '/_authenticated/_student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/_student/stationary': typeof AuthenticatedStudentStationaryRoute
  '/_authenticated/_admin/admin/bookings': typeof AuthenticatedAdminAdminBookingsRoute
  '/_authenticated/_admin/admin/equipment': typeof AuthenticatedAdminAdminEquipmentRoute
  '/_authenticated/_admin/admin/news': typeof AuthenticatedAdminAdminNewsRoute
  '/_authenticated/_admin/admin/projects': typeof AuthenticatedAdminAdminProjectsRoute
  '/_authenticated/_admin/admin/requests': typeof AuthenticatedAdminAdminRequestsRoute
  '/_authenticated/_admin/admin/schedule': typeof AuthenticatedAdminAdminScheduleRoute
  '/_authenticated/_admin/admin/statistics': typeof AuthenticatedAdminAdminStatisticsRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/update-password'
    | '/dashboard'
    | '/news'
    | '/projects'
    | '/admin'
    | '/booking'
    | '/portable'
    | '/profile'
    | '/stationary'
    | '/admin/bookings'
    | '/admin/equipment'
    | '/admin/news'
    | '/admin/projects'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/statistics'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/update-password'
    | '/dashboard'
    | '/news'
    | '/projects'
    | '/booking'
    | '/portable'
    | '/profile'
    | '/stationary'
    | '/admin/bookings'
    | '/admin/equipment'
    | '/admin/news'
    | '/admin/projects'
    | '/admin/requests'
    | '/admin/schedule'
    | '/admin/statistics'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/login'
    | '/update-password'
    | '/_authenticated/_admin'
    | '/_authenticated/_student'
    | '/_authenticated/dashboard'
    | '/_authenticated/news'
    | '/_authenticated/projects'
    | '/_public/'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_student/booking'
    | '/_authenticated/_student/portable'
    | '/_authenticated/_student/profile'
    | '/_authenticated/_student/stationary'
    | '/_authenticated/_admin/admin/bookings'
    | '/_authenticated/_admin/admin/equipment'
    | '/_authenticated/_admin/admin/news'
    | '/_authenticated/_admin/admin/projects'
    | '/_authenticated/_admin/admin/requests'
    | '/_authenticated/_admin/admin/schedule'
    | '/_authenticated/_admin/admin/statistics'
    | '/_authenticated/_admin/admin/users'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  UpdatePasswordRoute: typeof UpdatePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/update-password': {
      id: '/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof UpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/news': {
      id: '/_authenticated/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthenticatedNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_student': {
      id: '/_authenticated/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_student/stationary': {
      id: '/_authenticated/_student/stationary'
      path: '/stationary'
      fullPath: '/stationary'
      preLoaderRoute: typeof AuthenticatedStudentStationaryRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/profile': {
      id: '/_authenticated/_student/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/portable': {
      id: '/_authenticated/_student/portable'
      path: '/portable'
      fullPath: '/portable'
      preLoaderRoute: typeof AuthenticatedStudentPortableRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_student/booking': {
      id: '/_authenticated/_student/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof AuthenticatedStudentBookingRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/statistics': {
      id: '/_authenticated/_admin/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AuthenticatedAdminAdminStatisticsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/schedule': {
      id: '/_authenticated/_admin/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AuthenticatedAdminAdminScheduleRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/requests': {
      id: '/_authenticated/_admin/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/projects': {
      id: '/_authenticated/_admin/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/news': {
      id: '/_authenticated/_admin/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminAdminNewsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/equipment': {
      id: '/_authenticated/_admin/admin/equipment'
      path: '/equipment'
      fullPath: '/admin/equipment'
      preLoaderRoute: typeof AuthenticatedAdminAdminEquipmentRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/bookings': {
      id: '/_authenticated/_admin/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminBookingsRoute: typeof AuthenticatedAdminAdminBookingsRoute
  AuthenticatedAdminAdminEquipmentRoute: typeof AuthenticatedAdminAdminEquipmentRoute
  AuthenticatedAdminAdminNewsRoute: typeof AuthenticatedAdminAdminNewsRoute
  AuthenticatedAdminAdminProjectsRoute: typeof AuthenticatedAdminAdminProjectsRoute
  AuthenticatedAdminAdminRequestsRoute: typeof AuthenticatedAdminAdminRequestsRoute
  AuthenticatedAdminAdminScheduleRoute: typeof AuthenticatedAdminAdminScheduleRoute
  AuthenticatedAdminAdminStatisticsRoute: typeof AuthenticatedAdminAdminStatisticsRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminBookingsRoute: AuthenticatedAdminAdminBookingsRoute,
    AuthenticatedAdminAdminEquipmentRoute:
      AuthenticatedAdminAdminEquipmentRoute,
    AuthenticatedAdminAdminNewsRoute: AuthenticatedAdminAdminNewsRoute,
    AuthenticatedAdminAdminProjectsRoute: AuthenticatedAdminAdminProjectsRoute,
    AuthenticatedAdminAdminRequestsRoute: AuthenticatedAdminAdminRequestsRoute,
    AuthenticatedAdminAdminScheduleRoute: AuthenticatedAdminAdminScheduleRoute,
    AuthenticatedAdminAdminStatisticsRoute:
      AuthenticatedAdminAdminStatisticsRoute,
    AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentBookingRoute: typeof AuthenticatedStudentBookingRoute
  AuthenticatedStudentPortableRoute: typeof AuthenticatedStudentPortableRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
  AuthenticatedStudentStationaryRoute: typeof AuthenticatedStudentStationaryRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentBookingRoute: AuthenticatedStudentBookingRoute,
  AuthenticatedStudentPortableRoute: AuthenticatedStudentPortableRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
  AuthenticatedStudentStationaryRoute: AuthenticatedStudentStationaryRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewsRoute: typeof AuthenticatedNewsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewsRoute: AuthenticatedNewsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  UpdatePasswordRoute: UpdatePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
