// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifgcxlijwjqvnekpcrkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZ2N4bGlqd2pxdm5la3Bjcmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODc3NDk5ODUsImV4cCI6MjEwMzMyNTk4NX0.sDUqVhLCfrZm4ezriPHtn-zgT5lCBxmn66umc4KLQ80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});