// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ypbcsyaeuammtoayyrzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwYmNzeWFldWFtbXRvYXl5cnpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg5MTcyNjMsImV4cCI6MjA5NDQ5MzI2M30.0gMDRCByFS0yEj8zt4v8Rj5TYOu0yCCrkKK22Jvz9Ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});